#!/usr/bin/env bash
# Install Nginx (if not already installed)
sudo apt-get update
sudo apt-get install -y nginx

# Start Nginx service (if not already running)
sudo service nginx start

# Create a default Nginx configuration file
sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        echo 'Holberton School for the win!';
        root /var/www/html;
    }

    # Custom 404 page
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Create the custom 404 page
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

# Reload Nginx to apply the changes
sudo service nginx reload
